### ISSUE TITLE
Browser producer cors error

### ISSUE THREAD

**Issue by andriy-tsvikla** [aws-samples/amazon-kinesis-video-streams-demos#138]
I am trying to run browser example as result i get this error in console

`Access to fetch at 'https://*.kinesisvideo.eu-central-1.amazonaws.com/putMedia' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

 [Link to config screenshot](https://prnt.sc/x709me)

Not sure where cors suppose to be configured. Please advise.

**Comment by anuar12** [comment]
Start and turn on this extension, it should fix your problem (it happens when running on localhost)

**Comment by andriy-tsvikla** [comment]
Extension did not help.
From my understanding its suppose to be configured on kinesis side and not by browser extension.

**Comment by MuhammedBeyhanUS** [comment]
@andriy-tsvikla were you able to solve the problem?

**Comment by MuhammedBeyhanUS** [comment]
> Extension did not help.
> From my understanding kinesis protected by cors policy and localhost is not in whitelist, is that correct?

Hi, i am having the same problem now. Were you able to solve the problem?

**Comment by andriy-tsvikla** [comment]
@MuhammedBeyhanUS since it was for testing only i sent produced mkv to custom server and send data to kinesis stream from there
