### ISSUE TITLE
Pass AWS and stream link arguments in docker run

### ISSUE THREAD

**Issue by luisberga** [aws-samples/amazon-kinesis-video-streams-demos#198]
How can I pass the:

`AWS_ACCESS_KEY_ID=<AWS_ACCESS_KEY_ID> AWS_SECRET_ACCESS_KEY=<AWS_SECRET_ACCESS_KEY> ./kvs_gstreamer_sample <STREAM_NAME> <RTSP_URL> `

Directly in the docker run?

**Comment by floydrodery** [comment]
I'm also curious and having this issue.

**Comment by sirknightj** [comment]
```
docker exec -it <image_id> /bin/bash -c "<CREDENTIALS> ./kvs_gstreamer_sample <StreamName> <RtspUrl>"
```

Reference: https://docs.docker.com/engine/reference/commandline/exec/

**Comment by sirknightj** [comment]
We've updated the documentation to include instructions for this: https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/examples-rtsp.html
