### ISSUE TITLE
Does Kinesis Video Stream Support UDP

### ISSUE THREAD

**Issue by mdhruv1** [aws-samples/amazon-kinesis-video-streams-demos#220]
I am looking at the documentation. Do we know if Kinesis Video Stream does it support UDP or only HTTP

Any help here would be helpfull.

**Comment by sirknightj** [comment]
Hi @mdhruv1, apologies for the late reply.

To access the Kinesis Video Streams service, TCP (HTTP POST and GET) must be used.

For example, [putMedia]( https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_dataplane_PutMedia.html#API_dataplane_PutMedia_RequestSyntax).

Please let me know if you have any further questions!
