### ISSUE TITLE
Create GStreamer Demo/Sample Application which takes RTSP url and goes to kvssink

### ISSUE THREAD

**Issue by hassanctech** [aws-samples/amazon-kinesis-video-streams-demos#23]

**Comment by lherman-cs** [comment]
I think this example already takes RTSP url and push it to KVS, https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/samples/kvs_gstreamer_multistream_sample.cpp. Maybe we should just modify it to use kvssink instead to simplify it?

**Comment by sirknightj** [comment]
This sample (kvssink_gstreamer_sample) goes straight from rtsp to kvssink (whereas the one linked by @lherman-cs (kvs_gstreamer_sample) goes from rtspsrc to appsink).

https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/blob/master/samples/kvssink_gstreamer_sample.cpp
