### ISSUE TITLE
ERROR running producer C canary

### ISSUE THREAD

**Issue by S0UL4** [aws-samples/amazon-kinesis-video-streams-demos#267]
Hello guys,
after building the executable and added the iot credentials, i tried to run the KvsProducerSampleCloudwatch but i always get this error below:

2022-12-06 13:17:33 ERROR   main(): operation returned status code: 0x00000009
2022-12-06 13:17:33 ERROR   main(): operation returned status code: 0x00000009

![Screenshot from 2022-12-06 14-33-25](https://user-images.githubusercontent.com/62818840/205926211-6c982d06-e272-4dbe-9907-b957dfd8a10f.png)

**Comment by MushMal** [comment]
The code is defined here: https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/master/src/common/include/com/amazonaws/kinesis/video/common/CommonDefs.h#L472

Make sure the paths you specify are correct

**Comment by S0UL4** [comment]
Thanks @MushMal , Should i also create canary/configure cloudwatch on AWS ?

**Comment by MushMal** [comment]
I am not familiar with the details but some information is available in the readme file: https://github.com/aws-samples/amazon-kinesis-video-streams-demos/tree/master/canary/producer-c#readme

**Comment by niyatim23** [comment]
Closing this issue since the discussion is stale. Feel free to reopen this if the problem persists
