### ISSUE TITLE
RTSP demo application disconnecting after some time

### ISSUE THREAD

**Issue by 3AGSystemsShervin** [aws-samples/amazon-kinesis-video-streams-demos#270]
Hi team,

I have setup two RTSP cameras on my network and I have followed the RTSP demo application (https://github.com/aws-samples/amazon-kinesis-video-streams-demos/tree/master/producer-cpp/docker-rtsp) that uses docker desktop on Windows to send  both streams to Amazon Kinesis Video. I was successfully able to see each video feed on amazon console for each stream. However after I left the sample to run for some time. After some time the process shuts down and the stream is stopped. I can see some warnings before the error "Error received from element source: Could not read from resource." is thrown. Seems the first warning that is thrown is " curlCompleteSync(): curl perform failed for url https://xxxxxxxxxxxxxx.us-west-2.amazonaws.com/putMedia with result Failure when receiving data from the peer: OpenSSL SSL_read: Connection reset by peer, errno 104". I have seen some suggestions on threads on this site which suggested to turn down the camera stream "Frame Size", "Max Bit Rate", "Target Quality" and finally "Intra Frame Period". When I was running at ("Frame Size" =  "1920 1080") sometimes it would stop stream after about 20-30 mins. But since I have turned it down to ("Frame Size" =  "640 360", "Target Quality" = "Medium",  "Max Bit Rate" = "1 MBps" and   "Intra Frame Period" = "1s")  and it actually ran for about 2.5 hours before shutting down with the same issue. I have blacked out all the keys and credentials and  attached two screen shots to this message. They contain all the warnings and the error that is thrown before the process is shut down. We plan to use architecture for a client and we will be adding many more cameras to the network. 

Can you please guide me to what can be causing this issue and ways to improve this so the process does not shut down. Also please let me know if you need anything else.

Thanks for your time

![Screenshot1](https://user-images.githubusercontent.com/68082681/207779250-1890b2a1-bb28-4175-97bd-6e5bd256809e.png)
![image](https://user-images.githubusercontent.com/68082681/207779275-3f3bb884-aa91-4282-8475-8d08d0742ee4.png)

**Comment by 3AGSystemsShervin** [comment]
@MushMal Any help would be appreciated

**Comment by ingcarlos91** [comment]
> @disa6302 @MushMal Any help would be appreciated

Hello, I hope you are very well. Could you fix the error? Where did you set the variables you name? I'm trying to stream from RTSP but it disconnects after a couple of seconds

**Comment by MushMal** [comment]
I don't see anything actionable in the picture of the log - seems that you might have an issue with the connection being dropped from your RTSP upstream. I would recommend removing kvs from the equation and debugging your RTSP stream in the vm you are using and check what's causing the connection drop.

**Comment by sirknightj** [comment]
[`rtspsrc`](https://gstreamer.freedesktop.org/documentation/rtsp/rtspsrc.html?gi-language=c) sends an [EOS](https://gstreamer.freedesktop.org/documentation/additional/design/events.html?gi-language=c#eos) when it stops receiving data from the rtsp source (e.g. internet disruption), which we see in the logs:
```
WARNING: from element /GstPipeline:pipeline0/GstRTSPSrc:rtspsrc0: Could not read from resource.
Additional debug info:
../gst/rtsp/gstrtspsrc.c(5819): gst_rtspsrc_loop_udp (): /GstPipeline:pipeline0/GstRTSPSrc:rtspsrc0:
The server closed the connection.
[INFO ] [19-09-2023 16:53:43:561.222 GMT] EOS Event received in sink for demo-stream
```

You will need to restart the application when this happens, to have `rtspsrc` try to connect to the camera again. Once the EOS is sent, the session finishes. The session needs to be re-initialized from the beginning.

Some suggestions for doing this may be to use a [use a `while true` loop](https://catalog.us-east-1.prod.workshops.aws/workshops/b95b9381-baf0-4bef-ba31-63817d54c2a6/en-US/3-stream/2-sample-app#if-you-use-pre-downloaded-video), or looking into a using systems and service manager such as `systemd` to restart the application for you.
