### ISSUE TITLE
NetworkingError: Network Failure

### ISSUE THREAD

**Issue by sumitmandal13** [aws-samples/amazon-kinesis-video-streams-demos#292]
When running http://localhost:8080/dist/ even after getting correct credentials , I am getting **NetworkingError: Network Failure**

**Comment by sirknightj** [comment]
Please make sure all the fields are filled out. Unlike the [WebRTC JS](https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html) sample, this one does not default if the field isn't filled out. Feel free to create a PR for it if you'd like.

Service: `kinesisvideo`
Region: `us-west-2`
Endpoint: `https://kinesisvideo.us-west-2.amazonaws.com`

List of endpoints: https://docs.aws.amazon.com/general/latest/gr/akv.html
