### ISSUE TITLE
Subject: Using gst/gst-kvs-plugin on EC2 Linux to extract frames from server

### ISSUE THREAD

**Issue by tungnguyen2345** [aws-samples/amazon-kinesis-video-streams-demos#331]
Hi,

I'm encountering issues while attempting to run the gst/gst-kvs-plugin examples on EC2 Linux. My goal is to see whether gstreamer can extract frames from a stream video on server. I got the following error when testing the example, and eventually I will add a `filesrc location` command.

**1. Linux version for vtenc_h264_hw:**

When running the following command:
```bash
gst-launch-1.0 autovideosrc ! vtenc_h264_hw max-keyframe-interval=30 bitrate=500 ! kvsplugin stream-name=ScaryTestStream channel-name="ScaryTestChannel" log-level=3
```

I receive the following warning:

`WARNING: erroneous pipeline: no element "vtenc_h264_hw`

It seems like there might be compatibility issues with certain elements on my ec2 Linux. With that, I assume the stream is followed by the example stream "Foo" from this [link](https://docs.aws.amazon.com/streams/latest/dev/fundamental-stream.html).

I appreciate any guidance on resolving these issues.

**Comment by sirknightj** [comment]
Hi,

The vtenc_h264_hw element is only available on MacOS, as it's a hardware encoder. Check out the [gstreamer documentation](https://gstreamer.freedesktop.org/documentation/applemedia/vtenc_h264_hw.html?gi-language=c), for more information on that. You may want to check out x264enc.

I noticed the link is pointing to Kinesis Data Streams, whereas this repository contains examples for Kinesis Video Streams. If you want to try uploading a video to Kinesis Video Streams, I recommend checking out [CPP producer](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp) and using the [kvssink plugin](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/examples-gstreamer-plugin.html) or the kvs_gstreamer_sample to send video to Kinesis Video Streams. You can also check out the [workshop](https://catalog.us-east-1.prod.workshops.aws/workshops/b95b9381-baf0-4bef-ba31-63817d54c2a6/en-US) to explore KVS.
