### ISSUE TITLE
Webrtc Canary should delete signaling channels after terminated

### ISSUE THREAD

**Issue by lherman-cs** [aws-samples/amazon-kinesis-video-streams-demos#47]
Since it's very likely that the canary is run multiple times with different channels, it's important to always clean up these channels to make sure that we don't hit the limit.

**Comment by MushMal** [comment]
The signaling canary itself does delete the channel. We need to apply a similar strategy to others

**Comment by lherman-cs** [comment]
This issue has been fixed by https://github.com/aws-samples/amazon-kinesis-video-streams-demos/pull/65. Closing.
