### ISSUE TITLE
Fix end to end frame latency measurement in webrtc canary

### ISSUE THREAD

**Issue by disa6302** [aws-samples/amazon-kinesis-video-streams-demos#76]
When frames are generated a higher rate, the number of end to end latencies data generated might be more within the current 30 second cloudwatch metric duration. This leads to the following error: 

```
ERROR   operator()(): Failed to put sample metric data: Unable to parse ExceptionName: RequestEntityTooLarge Message: Request size 41154 exceeded 40960 bytes"
```

The metric emitting frequency must be based on the frame rate to avoid this issue and to ensure we do not lose data points.

**Comment by MushMal** [comment]
Interesting... This leads to a question whether we want to do some sort of aggregation on the client side first of all?

**Comment by disa6302** [comment]
The metric is aggregated automatically by cloudwatch if the data is stored in a vector. Currently, the frame latencies are added to the vector every time it is calculated and an aggregated data is what is published on cloudwatch. I think aggregating and publishing a single data is a better idea instead of letting cloudwatch to handle it.

**Comment by MushMal** [comment]
Perhaps we need to do multi-level aggregation? The client will be doing high-resolution aggregation reporting whereas the aggregation for dashboard will do more low-resolution aggregation. This way we could see some of the spikes if we look at the actual metrics on the CW?

**Comment by lherman-cs** [comment]
This issue has been fixed by https://github.com/aws-samples/amazon-kinesis-video-streams-demos/issues/76. Closing.
