### ISSUE TITLE
putMediaCall is failling

### ISSUE THREAD

**Issue by samuelcardosozup** [aws-samples/amazon-kinesis-video-streams-demos#83]
Trying to use the code as is, I'm getting:

"message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."

When calling:

https://github.com/aws-samples/amazon-kinesis-video-streams-demos/blob/master/producer-js/browser-based-ingestion/src/putMediaCall.js

It seams that AWS.sign method is not accepting Kinesis connection.

**Comment by MushMal** [comment]
You need to integrate your AWS credentials. Resolving.

**Comment by samuelcardosozup** [comment]
> You need to integrate your AWS credentials. Resolving.

It was integrated. The problem was regarded with the framerate. When slowing down to 5 (instead of 30) it started working.

Thanks for the support. Hope it helps.

**Comment by MushMal** [comment]
This doesn't make sense. You stated that you are getting

"message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."


This is returned from the backend AuthZ indicating AWS SigV4 mismatch. So it's an indication that:

* You have not integrated with auth
* You did not specify a session token if it's needed
* There is a corruption somewhere in the memory
