### ISSUE TITLE
Problem to start streaming from a rtsp url

### ISSUE THREAD

**Issue by pabloedm** [aws-samples/amazon-kinesis-video-streams-demos#9]
Hey guys, 
Im trying to use the rtsp-docker.
So, I built it with `docker build -t rtspdockertest .`
Then I tried to run it like its described in the readme page, with `sudo docker run --network host --rm -it -e AWS_DEFAULT_REGION=us-east-1 rtspdockertest <AWS_ACCESS_KEY_ID> <AWS_SECRET_ACCESS_KEY> ./kinesis_video_gstreamer_sample_app <STREAM_NAME> <RTSP_URL>`

I got the following error:
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"<AWS_ACCESS_KEY_ID>\": executable file not found in $PATH": unknown.`

Am I doing something wrong here? Can you help me?

**Comment by disa6302** [comment]
Hello @pabloedm , 

Can you break down the steps? 

Run `sudo docker run --network host --rm -it -e AWS_DEFAULT_REGION=us-east-1 rtspdockertest` first

And then once you are in, run `<AWS_ACCESS_KEY_ID> <AWS_SECRET_ACCESS_KEY> ./kinesis_video_gstreamer_sample_app <STREAM_NAME> <RTSP_URL>`

Make sure to export the access key id and secret access key once you enter the docker container.

**Comment by disa6302** [comment]
One more thing, please make sure to pull in the latest changes in the image. Let me know if you face any issues :)

**Comment by pabloedm** [comment]
Hello @disa6302 
Thanks for your responses, I managed to make it work following your instructions.
